In [1]:
import numpy as np 
import os
path = '/CSNG/baroni/mozaik-models/Images_for_optostim/experiment_1'
files = [os.path.join(path, f) for f in os.listdir(path)]
file_save = [os.path.join(path, f) for f in os.listdir(path)]

for file in files:
    
    print(f"Processing file: {file}")
    x = np.load(file)
    assert x.max() == 3.
    print(f"Loaded array: {x}")
    x = x / 3.
    np.save(file, x)


Processing file: /CSNG/baroni/mozaik-models/Images_for_optostim/experiment_1/grating_ori=000_rot90_flipped.npy
Loaded array: [[2.62932539 2.62932539 2.62932539 ... 2.29939318 0.99446303 0.99446303]
 [2.62932539 2.62932539 2.62932539 ... 2.29939318 0.99446303 0.99446303]
 [2.62932539 2.62932539 2.62932539 ... 1.75294292 0.99446303 0.99446303]
 ...
 [1.79309154 1.55915046 1.55915046 ... 2.11510682 2.08842039 2.08842039]
 [1.55882478 1.55882478 1.55882478 ... 2.93885899 2.08842039 2.08842039]
 [1.55882478 1.55882478 1.2107991  ... 2.93885899 2.08842039 2.08842039]]
Processing file: /CSNG/baroni/mozaik-models/Images_for_optostim/experiment_1/grating_ori=000_rot180_flipped.npy
Loaded array: [[1.55882478 1.55882478 1.79309154 ... 2.62932539 2.62932539 2.62932539]
 [1.55882478 1.55882478 1.55915046 ... 2.62932539 2.62932539 2.62932539]
 [1.2107991  1.55882478 1.55915046 ... 2.62932539 2.62932539 2.62932539]
 ...
 [2.93885899 2.93885899 2.11510682 ... 1.75294292 2.29939318 2.29939318]
 [2.0884